### ISSUE TITLE
Does it work?

### ISSUE THREAD

**Issue by philip-iii** [magcius/gnome-shell-wobbly-windows#1]
I was fiddling about with gnome shell yesterday and in between things I installed both the wobbly windows extension and the gravity windows extension. While after some tweaking I was able to get the gravity windows extension to work, I couldn't say the same about the wobbly windows. There were no obvious error messages either. Initially it complained about begin-grab-op and end-grab-op not being defined, to which I responded by changing these to grab-op-begin and grab-op-end respectively. While this did solve the problem with gravity windows and it worked subsequently, I had no luck with wobbly windows.

So, reiterating my question: Does it work at all? Or is it just not supposed to be quite there yet. And if it is the case, what is missing and what is left to be done? What are the prospects - is there any chance we are going to see this working? Is there anything that can be done to help with this?

Cheers!

Tested on Ubuntu Gnome Shell Remix (12.04) with Gnome Shell 3.4 and Linux Mint 13 RC with Cinnamon 1.4 (which is a different type of a beast I didn't expect it to work there yet, but at least in theory it should.. sometime in the future).

**Comment by magcius** [comment]
It's very silly. Clutter and mutter changes broke it. I may replace it with a geometry shader one day.

**Comment by magcius** [comment]
http://www.youtube.com/watch?v=5ERpE7AgfJo

this was what the WIP looked like

**Comment by philip-iii** [comment]
Ah... one of the joys of evolving software in the open source domain, eh? 
LOL, looks quite goofy ;-) Still, shows it could be done, and how. Is there any way to fix it so it works with the changed clutter and mutter (or rather how much effort would it be)? Perhaps someone else could pick up on it until a better solution is available...

Cheers for the quick replies!

**Comment by magcius** [comment]
You are free to fork and try. Good luck.

**Comment by stuaxo** [comment]
I guess it is now up on extensions.gnome.org
https://extensions.gnome.org/extension/669/wobbly-windows/

Not sure if there have been any changes, but it works to an extent.
