### ISSUE TITLE
Stop spring size from going negative

### ISSUE THREAD

**Issue by stuaxo** [magcius/gnome-shell-wobbly-windows#3]
Hi,
  I know it's years since you wrote this.    I think the main thing that makes this look a bit odd is that when you drag quickly, it can actually end up showing parts of the back of the window. 

This shouldn't happen, I guess as the segments of the grid get smaller, the spring should get more resistive, idea of where I'd change the code so that the grid segments can never have a negative width or height ?

S

**Comment by SleepswithGators** [comment]
Can you replicate this?

**Comment by stuaxo** [comment]
I tried installing just now and it wasn't working properly.

My bug here is trying to explain the sort of fold in the top of the window on this screenshot

https://extensions.gnome.org/extension/669/wobbly-windows/


It could be that the spring settings are different to the original addon in compiz.

**Comment by magcius** [comment]
I haven't touched this repo for six years, and I stopped contributing to GNOME about three years ago. Apologies, but I can't help you much on this end here. I was not the one who submitted the extension to the repo -- someone else probably uploaded it (without my permission, mind you).

Sorry.
